spring:
  application:
    name: QUEUE-NOTIFACTION.SERVICE
server:
  port: 10084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true