spring:
  application:
    name: QUEUE-TASK-JOB.SERVICE
server:
  port: 10081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

