spring:
  application:
    name: QUEUE-MISC.SERVICE
server:
  port: 10085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
